version: '2'
# 这个docker环境是给开发者在自己的电脑上部署的
# 你可以用 ./start_develop.sh 来自动化创建环境
services:

  blog_backend:
    restart: always
    build: ./flask
    ports:
      - "5000:5000"
    volumes:
      - ../blog:/opt/blog
      - /data/blog/www/static:/opt/static
    command: sleep 100000000000000000000
