version: '2'
# 这个docker环境是给开发者在自己的电脑上部署的
# 你可以用 ./start_develop.sh 来自动化创建环境
services:

  blog_nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - blog_backend
    ports:
      - "80:80"
    volumes:
      - /data/blog/www/static:/opt/blog/static
      - /data/blog/media:/opt/blog/media

  blog_backend:
    restart: always
    build: ./flask

    ports:
      - "8000:8000"
    volumes:
      - ../blog:/opt/blog
      - /data/blog/www/static:/opt/static
    command: uwsgi --ini uwsgi.ini
