---
- name: Update apt cache (cache valid 1 day)
  apt: update_cache=yes cache_valid_time=86400

- name: Set hostname for servers
  hostname:
    name: "{{ hostname }}"

- name: install NTP
  apt: name={{ item }} state=installed
  with_items:
  - python-selinux
  - ntp

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
   - restart ntp

- name: Add or modify nofile soft limit
  pam_limits: domain=* limit_type=soft limit_item=nofile value=65335 use_max=yes

- name: Add or modify nofile hard limit
  pam_limits: domain=* limit_type=hard limit_item=nofile value=65335 use_max=yes

# root 的limit必须要单独设置, 不然就不生效
- name: Add or modify nofile soft limit for root
  pam_limits: domain=root limit_type=soft limit_item=nofile value=65335 use_max=yes

- name: Add or modify nofile hard limit for root
  pam_limits: domain=root limit_type=hard limit_item=nofile value=65335 use_max=yes

- name: Vim - Make sure vim-tiny is uninstalled
  apt: pkg=vim-tiny state=absent

- name: Vim - Make sure VIM is installed
  apt: pkg=vim state=present

- name: Vim - remove Nano
  apt: pkg=nano state=absent

- name: install python tools
  apt: pkg={{ item }} state=installed
  with_items:
    - python-pip
    - python-dev
    - python-setuptools
    - python-virtualenv
    - python-psutil

- name: install System tools
  apt: pkg={{ item }} state=installed
  with_items:
    - make
    - build-essential
    - tcl8.5
    # 上面的包确保 glances 可以安装
    - dstat
    - htop
    - sysstat
    - glances
    - vnstat
    - vnstati
