---
- hosts: all
  strategy: free
  tags: common
  remote_user: root
  become: yes
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
  roles:
    - {role: common, stage: staging}


- hosts: all
  tags: docker
  remote_user: root
  become: yes
  roles:
    - {role: docker.ubuntu}


- hosts: all
  strategy: free
  tags: netdata
  remote_user: root
  become: yes
  vars:
    - web_port: 19999
  roles:
    - {role: netdata, stage: staging}


- hosts: redis
  tags: redis
  remote_user: root
  become: yes
  roles:
    - {role: redis}


- hosts: backend
  strategy: free
  tags: backend
  remote_user: root
  become: yes
  roles:
    - {role: backend}
