---
- name: "Install pre-requisites"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - gcc
    - git
    - libmnl-dev
    - make
    - pkg-config
    - uuid-dev
    - zlib1g-dev


#Clone reopo into source and keep it for later (upgrade)
- name: "Clone repo netdata"
  git:
    clone: yes
    update: yes
    repo: https://github.com/firehol/netdata.git
    dest: /usr/src/netdata
    version: v1.6.0
  register: gitupdate

- name: "Installation netdata"
  shell: cd /usr/src/netdata/ && ./netdata-installer.sh --dont-wait --libs-are-really-here
  notify:  Restart netdata
  when: gitupdate.changed

- name: "Upload netdata config"
  template: src=templates/netdata.conf.j2 dest=/etc/netdata/netdata.conf mode=0644
  notify:  Restart netdata

- name: "Upload netdata health config"
  template: src=templates/health_alarm_notify.conf.j2 dest=/etc/netdata/health_alarm_notify.conf mode=0644
  notify:  Restart netdata

- name: Make monitor dir
  file: path=/data/monitor mode=0755 state=directory

- name: Upload netdata docker
  synchronize: src=../monitor/docker dest=/data/monitor delete=yes rsync_opts=--exclude=*.pyc,--exclude=.DS_Store
  register: docker_config

- name: Rebuild netdata nginx containers
  shell: docker-compose -f netdata-nginx.yml up -d --build chdir=/data/monitor/docker
  when: docker_config.changed
  ignore_errors: yes

- name: Start docker containers if not running
  shell: docker-compose -f netdata-nginx.yml up -d --build chdir=/data/monitor/docker
  when: docker_config.changed == False
  ignore_errors: yes

- name: Restart docker containers if already running
  shell: docker-compose -f netdata-nginx.yml restart chdir=/data/monitor/docker
  when: docker_config.changed == False
  ignore_errors: yes

# we keep the sources for upgrades
#- name: "Clean git repo"
#  file:
#    path: /usr/src/netdata
#    state: absent


#Optional: use your own registry
#- lineinfile:
#    dest: /etc/netdata/netdata.conf
#    regexp: '^\t# registry to announce.*'
#    line: '\t registry to announce = http://your-registry-server.comp.tld:19999'
#    backrefs: yes


#Optional: Disable notifications
#- lineinfile:
#    dest: /etc/netdata/health_alarm_notify.conf
#    regexp: '^SEND_EMAIL="YES"'
#    line: 'SEND_EMAIL="NO"'
#    backrefs: yes


#ToDo Uninstaller -  see netdata-uninstaller.sh
