---
- name: Upload docker config
  remote_user: root
  become: yes
  synchronize: src=../docker dest=/data/canting/src delete=yes rsync_opts=--exclude=.DS_Store
  register: docker_config

- name: Start docker containers if not running
  shell: docker-compose -f server-database-{{ database_type }}.yml up -d chdir=/data/canting/src/docker
  when: docker_config.changed == False

- name: Rebuild docker containers
  shell: docker-compose -f server-database-{{ database_type }}.yml up -d --build chdir=/data/canting/src/docker
  when: docker_config.changed
