---
- name: Upload docker config
  remote_user: root
  become: yes
  synchronize: src=../docker dest=/data/blog/src delete=yes rsync_opts=--exclude=.DS_Store

- name: Start docker containers
  shell: docker-compose -f server-redis.yml up -d chdir=/data/blog/src/docker
