---
- name: Rebuild docker containers
  shell: docker-compose -f server-web.yml up -d --build chdir=/data/blog/src/docker
  when: is_docker_file_changed

- name: Start docker containers if not running
  shell: docker-compose -f server-web.yml up -d chdir=/data/blog/src/docker
  when: is_docker_file_changed == False

# 先重启 backend 容器
- name: Restart blog backend docker containers
  shell: docker-compose -f server-web.yml restart blog_backend chdir=/data/blog/src/docker
  register: restart_containers
- debug: var=restart_containers.stdout_lines

# 使 nginx 容器在 backend 容器之后重启
- name: Restart nginx docker container
  shell: docker-compose -f server-web.yml restart blog_nginx chdir=/data/blog/src/docker

- name: Build deploy json
  copy: src=deploy.json dest=/data/blog/www/static/deploy.json mode=0644

