---
- name: Make blog source code dir
  remote_user: root
  become: yes
  file: path=/data/blog/src mode=0755 state=directory

#########################################
# 上传并处理 docker config 文件
#########################################
# 不上传 media.conf, 使用之后的 template task 生成 media.conf
- name: Upload docker config
  remote_user: root
  become: yes
  synchronize: src=../docker dest=/data/blog/src delete=yes rsync_opts=--exclude=.DS_Store
  register: docker_files



#########################################
# 上传并处理 source code
#########################################
- name: Upload source code
  synchronize: src=../blog dest=/data/blog/src delete=yes rsync_opts=--exclude=*.pyc,--exclude=.DS_Store
  register: code
